import Headers from './component/header/Headers'
import './globals.css'
import { Inter, Noto_Sans } from 'next/font/google'
import ReduxProvider from './store/ReduxProvider'
import Footer from './component/ui/Footer'

const inter = Inter({ subsets: ['latin'] })
const notosans = Noto_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'My Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={notosans.className}>
        <ReduxProvider>
          <Headers />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}
